# Generated by Django 5.0.4 on 2024-04-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='photoUrl',
            field=models.TextField(null=True),
        ),
    ]
