# Generated by Django 5.0.4 on 2024-04-10 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_service_photourl_service_image_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Category',
        ),
    ]
