# Generated by Django 5.0.4 on 2024-04-10 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.category'),
        ),
    ]
