# Generated by Django 5.0.4 on 2024-04-10 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_service_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='Category',
            new_name='category',
        ),
    ]
