# Generated by Django 5.0.4 on 2024-04-10 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_types'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Types',
            new_name='Type',
        ),
    ]
