# Generated by Django 5.0.4 on 2024-04-10 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_rename_types_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='types',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.type'),
        ),
    ]
