# Generated by Django 5.0.4 on 2024-04-10 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_service_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='types',
            field=models.ForeignKey(limit_choices_to={'category_id': models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.category')}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.type'),
        ),
    ]
