# Generated by Django 5.0.4 on 2024-04-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_service_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price_max',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='price_min',
            field=models.IntegerField(null=True),
        ),
    ]
